# Generated by Django 6.0.3 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybug_App", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registermodel",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("developer", "Developer"),
                    ("tester", "Tester"),
                ],
                max_length=20,
            ),
        ),
    ]
