# Generated by Django 6.0.3 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybug_App", "0002_alter_registermodel_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="registermodel",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
